### ISSUE TITLE
PIECE_END token

### ISSUE THREAD

**Issue by juancopi81** [AI-Guru/MMM-JSB#5]
Hi Tristan,

This is amazing! Thanks for sharing it. I was looking at the code and I was wondering about the PIECE_END token. I cannot find it. Do you have it somewhere? Also, it is the PIECE_START token placed at the start of each song? I think it is at the start of every partition based on the window_size_bars, hop_length_bars but wanted to confirm with you.

Thank again for this great code!

**Comment by AI-Guru** [comment]
Hi juancopi81!

Great question!

The MMM paper says:

> A piece begins with the PIECE START token. This process of nesting bars within a track and tracks within a piece is illustrated in Figure 1. Notably, we do not use a PIECE END token, as we can simply sample until we reach the nth TRACK END token if we wish to generate n tracks.

I was thinking about that very often. Turned out that I indeed never needed the PIECE_END token.

HTH!

Best,
Tristan

**Comment by juancopi81** [comment]
Hi Tristan,

Thank you very much for your kind and rapid response. Yes, it does help! :) 

Best regards,

Juan Carlos

**Comment by AI-Guru** [comment]
Hi Juan Carlos,

so great to hear!

Best wishes,
Tristan
